projects:
  api:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://api.buildastack.io/
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
